version: '3.7'
services:
  schedule-ui:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - schedule-back
    volumes:
      - ./client:/app
      - /app/node_modules

  schedule-back:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "3001:80"
    volumes:
      - ./server:/app
      - /app/node_modules

  